// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/carts/interfaces.go

// Package carts_test is a generated GoMock package.
package carts_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockCartAPI is a mock of CartAPI interface.
type MockCartAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCartAPIMockRecorder
}

// MockCartAPIMockRecorder is the mock recorder for MockCartAPI.
type MockCartAPIMockRecorder struct {
	mock *MockCartAPI
}

// NewMockCartAPI creates a new mock instance.
func NewMockCartAPI(ctrl *gomock.Controller) *MockCartAPI {
	mock := &MockCartAPI{ctrl: ctrl}
	mock.recorder = &MockCartAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartAPI) EXPECT() *MockCartAPIMockRecorder {
	return m.recorder
}

// CreateCart mocks base method.
func (m *MockCartAPI) CreateCart(ctx context.Context, payload bigcommerce.CartCreate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockCartAPIMockRecorder) CreateCart(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockCartAPI)(nil).CreateCart), ctx, payload)
}

// GetCart mocks base method.
func (m *MockCartAPI) GetCart(ctx context.Context, cartID string, includeRedirectURLs bool) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, cartID, includeRedirectURLs)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartAPIMockRecorder) GetCart(ctx, cartID, includeRedirectURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartAPI)(nil).GetCart), ctx, cartID, includeRedirectURLs)
}

// UpdateCart mocks base method.
func (m *MockCartAPI) UpdateCart(ctx context.Context, cartID string, payload bigcommerce.CartUpdate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", ctx, cartID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockCartAPIMockRecorder) UpdateCart(ctx, cartID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockCartAPI)(nil).UpdateCart), ctx, cartID, payload)
}

// DeleteCart mocks base method.
func (m *MockCartAPI) DeleteCart(ctx context.Context, cartID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCart", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCart indicates an expected call of DeleteCart.
func (mr *MockCartAPIMockRecorder) DeleteCart(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCart", reflect.TypeOf((*MockCartAPI)(nil).DeleteCart), ctx, cartID)
}

// AddCartItems mocks base method.
func (m *MockCartAPI) AddCartItems(ctx context.Context, cartID string, payload bigcommerce.CartItemsAdd) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItems", ctx, cartID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCartItems indicates an expected call of AddCartItems.
func (mr *MockCartAPIMockRecorder) AddCartItems(ctx, cartID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItems", reflect.TypeOf((*MockCartAPI)(nil).AddCartItems), ctx, cartID, payload)
}

// UpdateCartItem mocks base method.
func (m *MockCartAPI) UpdateCartItem(ctx context.Context, cartID, itemID string, payload bigcommerce.CartItemUpdate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, cartID, itemID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartAPIMockRecorder) UpdateCartItem(ctx, cartID, itemID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartAPI)(nil).UpdateCartItem), ctx, cartID, itemID, payload)
}

// DeleteCartItem mocks base method.
func (m *MockCartAPI) DeleteCartItem(ctx context.Context, cartID, itemID string) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, cartID, itemID)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockCartAPIMockRecorder) DeleteCartItem(ctx, cartID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockCartAPI)(nil).DeleteCartItem), ctx, cartID, itemID)
}

// ListCartMetafields mocks base method.
func (m *MockCartAPI) ListCartMetafields(ctx context.Context, cartID string) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartMetafields", ctx, cartID)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartMetafields indicates an expected call of ListCartMetafields.
func (mr *MockCartAPIMockRecorder) ListCartMetafields(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartMetafields", reflect.TypeOf((*MockCartAPI)(nil).ListCartMetafields), ctx, cartID)
}

// CreateCartMetafield mocks base method.
func (m *MockCartAPI) CreateCartMetafield(ctx context.Context, cartID string, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartMetafield", ctx, cartID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartMetafield indicates an expected call of CreateCartMetafield.
func (mr *MockCartAPIMockRecorder) CreateCartMetafield(ctx, cartID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartMetafield", reflect.TypeOf((*MockCartAPI)(nil).CreateCartMetafield), ctx, cartID, mf)
}

// UpdateCartMetafield mocks base method.
func (m *MockCartAPI) UpdateCartMetafield(ctx context.Context, cartID string, mfID int, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartMetafield", ctx, cartID, mfID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartMetafield indicates an expected call of UpdateCartMetafield.
func (mr *MockCartAPIMockRecorder) UpdateCartMetafield(ctx, cartID, mfID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartMetafield", reflect.TypeOf((*MockCartAPI)(nil).UpdateCartMetafield), ctx, cartID, mfID, mf)
}

// DeleteCartMetafield mocks base method.
func (m *MockCartAPI) DeleteCartMetafield(ctx context.Context, cartID string, mfID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartMetafield", ctx, cartID, mfID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartMetafield indicates an expected call of DeleteCartMetafield.
func (mr *MockCartAPIMockRecorder) DeleteCartMetafield(ctx, cartID, mfID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartMetafield", reflect.TypeOf((*MockCartAPI)(nil).DeleteCartMetafield), ctx, cartID, mfID)
}

// GetCheckout mocks base method.
func (m *MockCartAPI) GetCheckout(ctx context.Context, checkoutID string) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckout", ctx, checkoutID)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckout indicates an expected call of GetCheckout.
func (mr *MockCartAPIMockRecorder) GetCheckout(ctx, checkoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckout", reflect.TypeOf((*MockCartAPI)(nil).GetCheckout), ctx, checkoutID)
}

// ApplyCoupon mocks base method.
func (m *MockCartAPI) ApplyCoupon(ctx context.Context, checkoutID, code string) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCoupon", ctx, checkoutID, code)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyCoupon indicates an expected call of ApplyCoupon.
func (mr *MockCartAPIMockRecorder) ApplyCoupon(ctx, checkoutID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCoupon", reflect.TypeOf((*MockCartAPI)(nil).ApplyCoupon), ctx, checkoutID, code)
}

// RemoveCoupon mocks base method.
func (m *MockCartAPI) RemoveCoupon(ctx context.Context, checkoutID, code string) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCoupon", ctx, checkoutID, code)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCoupon indicates an expected call of RemoveCoupon.
func (mr *MockCartAPIMockRecorder) RemoveCoupon(ctx, checkoutID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCoupon", reflect.TypeOf((*MockCartAPI)(nil).RemoveCoupon), ctx, checkoutID, code)
}

// SetBillingAddress mocks base method.
func (m *MockCartAPI) SetBillingAddress(ctx context.Context, checkoutID string, addr bigcommerce.CheckoutAddressInput) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBillingAddress", ctx, checkoutID, addr)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBillingAddress indicates an expected call of SetBillingAddress.
func (mr *MockCartAPIMockRecorder) SetBillingAddress(ctx, checkoutID, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBillingAddress", reflect.TypeOf((*MockCartAPI)(nil).SetBillingAddress), ctx, checkoutID, addr)
}

// UpdateBillingAddress mocks base method.
func (m *MockCartAPI) UpdateBillingAddress(ctx context.Context, checkoutID, addrID string, addr bigcommerce.CheckoutAddressInput) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBillingAddress", ctx, checkoutID, addrID, addr)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBillingAddress indicates an expected call of UpdateBillingAddress.
func (mr *MockCartAPIMockRecorder) UpdateBillingAddress(ctx, checkoutID, addrID, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBillingAddress", reflect.TypeOf((*MockCartAPI)(nil).UpdateBillingAddress), ctx, checkoutID, addrID, addr)
}

// AddConsignment mocks base method.
func (m *MockCartAPI) AddConsignment(ctx context.Context, checkoutID string, consignment bigcommerce.CheckoutConsignmentInput) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConsignment", ctx, checkoutID, consignment)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddConsignment indicates an expected call of AddConsignment.
func (mr *MockCartAPIMockRecorder) AddConsignment(ctx, checkoutID, consignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsignment", reflect.TypeOf((*MockCartAPI)(nil).AddConsignment), ctx, checkoutID, consignment)
}

// UpdateConsignment mocks base method.
func (m *MockCartAPI) UpdateConsignment(ctx context.Context, checkoutID, consignID string, update bigcommerce.CheckoutConsignmentUpdate) (*bigcommerce.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConsignment", ctx, checkoutID, consignID, update)
	ret0, _ := ret[0].(*bigcommerce.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConsignment indicates an expected call of UpdateConsignment.
func (mr *MockCartAPIMockRecorder) UpdateConsignment(ctx, checkoutID, consignID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConsignment", reflect.TypeOf((*MockCartAPI)(nil).UpdateConsignment), ctx, checkoutID, consignID, update)
}

// ConvertCheckoutToOrder mocks base method.
func (m *MockCartAPI) ConvertCheckoutToOrder(ctx context.Context, checkoutID string) (*bigcommerce.CheckoutOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertCheckoutToOrder", ctx, checkoutID)
	ret0, _ := ret[0].(*bigcommerce.CheckoutOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertCheckoutToOrder indicates an expected call of ConvertCheckoutToOrder.
func (mr *MockCartAPIMockRecorder) ConvertCheckoutToOrder(ctx, checkoutID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertCheckoutToOrder", reflect.TypeOf((*MockCartAPI)(nil).ConvertCheckoutToOrder), ctx, checkoutID)
}

// CreateCartRedirectURLs mocks base method.
func (m *MockCartAPI) CreateCartRedirectURLs(ctx context.Context, cartID string) (*bigcommerce.CartRedirectURLs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartRedirectURLs", ctx, cartID)
	ret0, _ := ret[0].(*bigcommerce.CartRedirectURLs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartRedirectURLs indicates an expected call of CreateCartRedirectURLs.
func (mr *MockCartAPIMockRecorder) CreateCartRedirectURLs(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartRedirectURLs", reflect.TypeOf((*MockCartAPI)(nil).CreateCartRedirectURLs), ctx, cartID)
}
