// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/carts/interfaces.go

// Package carts_test is a generated GoMock package.
package carts_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockCartAPI is a mock of CartAPI interface.
type MockCartAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCartAPIMockRecorder
}

// MockCartAPIMockRecorder is the mock recorder for MockCartAPI.
type MockCartAPIMockRecorder struct {
	mock *MockCartAPI
}

// NewMockCartAPI creates a new mock instance.
func NewMockCartAPI(ctrl *gomock.Controller) *MockCartAPI {
	mock := &MockCartAPI{ctrl: ctrl}
	mock.recorder = &MockCartAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartAPI) EXPECT() *MockCartAPIMockRecorder {
	return m.recorder
}

// CreateCart mocks base method.
func (m *MockCartAPI) CreateCart(ctx context.Context, payload bigcommerce.CartCreate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockCartAPIMockRecorder) CreateCart(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockCartAPI)(nil).CreateCart), ctx, payload)
}

// GetCart mocks base method.
func (m *MockCartAPI) GetCart(ctx context.Context, cartID string, includeRedirectURLs bool) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, cartID, includeRedirectURLs)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartAPIMockRecorder) GetCart(ctx, cartID, includeRedirectURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartAPI)(nil).GetCart), ctx, cartID, includeRedirectURLs)
}

// UpdateCart mocks base method.
func (m *MockCartAPI) UpdateCart(ctx context.Context, cartID string, payload bigcommerce.CartUpdate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", ctx, cartID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockCartAPIMockRecorder) UpdateCart(ctx, cartID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockCartAPI)(nil).UpdateCart), ctx, cartID, payload)
}

// DeleteCart mocks base method.
func (m *MockCartAPI) DeleteCart(ctx context.Context, cartID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCart", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCart indicates an expected call of DeleteCart.
func (mr *MockCartAPIMockRecorder) DeleteCart(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCart", reflect.TypeOf((*MockCartAPI)(nil).DeleteCart), ctx, cartID)
}

// AddCartItems mocks base method.
func (m *MockCartAPI) AddCartItems(ctx context.Context, cartID string, payload bigcommerce.CartItemsAdd) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItems", ctx, cartID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCartItems indicates an expected call of AddCartItems.
func (mr *MockCartAPIMockRecorder) AddCartItems(ctx, cartID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItems", reflect.TypeOf((*MockCartAPI)(nil).AddCartItems), ctx, cartID, payload)
}

// UpdateCartItem mocks base method.
func (m *MockCartAPI) UpdateCartItem(ctx context.Context, cartID, itemID string, payload bigcommerce.CartItemUpdate) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, cartID, itemID, payload)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartAPIMockRecorder) UpdateCartItem(ctx, cartID, itemID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartAPI)(nil).UpdateCartItem), ctx, cartID, itemID, payload)
}

// DeleteCartItem mocks base method.
func (m *MockCartAPI) DeleteCartItem(ctx context.Context, cartID, itemID string) (*bigcommerce.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, cartID, itemID)
	ret0, _ := ret[0].(*bigcommerce.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockCartAPIMockRecorder) DeleteCartItem(ctx, cartID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockCartAPI)(nil).DeleteCartItem), ctx, cartID, itemID)
}

// CreateCartRedirectURLs mocks base method.
func (m *MockCartAPI) CreateCartRedirectURLs(ctx context.Context, cartID string) (*bigcommerce.CartRedirectURLs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartRedirectURLs", ctx, cartID)
	ret0, _ := ret[0].(*bigcommerce.CartRedirectURLs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartRedirectURLs indicates an expected call of CreateCartRedirectURLs.
func (mr *MockCartAPIMockRecorder) CreateCartRedirectURLs(ctx, cartID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartRedirectURLs", reflect.TypeOf((*MockCartAPI)(nil).CreateCartRedirectURLs), ctx, cartID)
}
