// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/webhooks/interfaces.go

// Package webhooks_test is a generated GoMock package.
package webhooks_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhooksAPI is a mock of WebhooksAPI interface.
type MockWebhooksAPI struct {
	ctrl     *gomock.Controller
	recorder *MockWebhooksAPIMockRecorder
}

// MockWebhooksAPIMockRecorder is the mock recorder for MockWebhooksAPI.
type MockWebhooksAPIMockRecorder struct {
	mock *MockWebhooksAPI
}

// NewMockWebhooksAPI creates a new mock instance.
func NewMockWebhooksAPI(ctrl *gomock.Controller) *MockWebhooksAPI {
	mock := &MockWebhooksAPI{ctrl: ctrl}
	mock.recorder = &MockWebhooksAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhooksAPI) EXPECT() *MockWebhooksAPIMockRecorder {
	return m.recorder
}

// ListWebhooks mocks base method.
func (m *MockWebhooksAPI) ListWebhooks(ctx context.Context, params map[string]string) ([]bigcommerce.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhooks", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhooks indicates an expected call of ListWebhooks.
func (mr *MockWebhooksAPIMockRecorder) ListWebhooks(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhooks", reflect.TypeOf((*MockWebhooksAPI)(nil).ListWebhooks), ctx, params)
}

// GetWebhook mocks base method.
func (m *MockWebhooksAPI) GetWebhook(ctx context.Context, hookID int) (*bigcommerce.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhook", ctx, hookID)
	ret0, _ := ret[0].(*bigcommerce.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhook indicates an expected call of GetWebhook.
func (mr *MockWebhooksAPIMockRecorder) GetWebhook(ctx, hookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhook", reflect.TypeOf((*MockWebhooksAPI)(nil).GetWebhook), ctx, hookID)
}

// GetWebhookEvents mocks base method.
func (m *MockWebhooksAPI) GetWebhookEvents(ctx context.Context, hookID int) ([]bigcommerce.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookEvents", ctx, hookID)
	ret0, _ := ret[0].([]bigcommerce.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookEvents indicates an expected call of GetWebhookEvents.
func (mr *MockWebhooksAPIMockRecorder) GetWebhookEvents(ctx, hookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookEvents", reflect.TypeOf((*MockWebhooksAPI)(nil).GetWebhookEvents), ctx, hookID)
}

// CreateWebhook mocks base method.
func (m *MockWebhooksAPI) CreateWebhook(ctx context.Context, payload bigcommerce.WebhookCreate) (*bigcommerce.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhook", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhook indicates an expected call of CreateWebhook.
func (mr *MockWebhooksAPIMockRecorder) CreateWebhook(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhook", reflect.TypeOf((*MockWebhooksAPI)(nil).CreateWebhook), ctx, payload)
}

// UpdateWebhook mocks base method.
func (m *MockWebhooksAPI) UpdateWebhook(ctx context.Context, hookID int, payload bigcommerce.WebhookUpdate) (*bigcommerce.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", ctx, hookID, payload)
	ret0, _ := ret[0].(*bigcommerce.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockWebhooksAPIMockRecorder) UpdateWebhook(ctx, hookID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockWebhooksAPI)(nil).UpdateWebhook), ctx, hookID, payload)
}

// DeleteWebhook mocks base method.
func (m *MockWebhooksAPI) DeleteWebhook(ctx context.Context, hookID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", ctx, hookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockWebhooksAPIMockRecorder) DeleteWebhook(ctx, hookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockWebhooksAPI)(nil).DeleteWebhook), ctx, hookID)
}
