// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/catalog/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/tools/catalog/interfaces.go -destination=internal/tools/catalog/mock_bc_test.go -package=catalog_test -mock_names=BigCommerceAPI=MockBigCommerceAPI
//

// Package catalog_test is a generated GoMock package.
package catalog_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockBigCommerceAPI is a mock of BigCommerceAPI interface.
type MockBigCommerceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBigCommerceAPIMockRecorder
	isgomock struct{}
}

// MockBigCommerceAPIMockRecorder is the mock recorder for MockBigCommerceAPI.
type MockBigCommerceAPIMockRecorder struct {
	mock *MockBigCommerceAPI
}

// NewMockBigCommerceAPI creates a new mock instance.
func NewMockBigCommerceAPI(ctrl *gomock.Controller) *MockBigCommerceAPI {
	mock := &MockBigCommerceAPI{ctrl: ctrl}
	mock.recorder = &MockBigCommerceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBigCommerceAPI) EXPECT() *MockBigCommerceAPIMockRecorder {
	return m.recorder
}

// BatchUpdateCategories mocks base method.
func (m *MockBigCommerceAPI) BatchUpdateCategories(ctx context.Context, updates []bigcommerce.CategoryUpdate) (*bigcommerce.BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateCategories", ctx, updates)
	ret0, _ := ret[0].(*bigcommerce.BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateCategories indicates an expected call of BatchUpdateCategories.
func (mr *MockBigCommerceAPIMockRecorder) BatchUpdateCategories(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateCategories", reflect.TypeOf((*MockBigCommerceAPI)(nil).BatchUpdateCategories), ctx, updates)
}

// BatchUpdateProducts mocks base method.
func (m *MockBigCommerceAPI) BatchUpdateProducts(ctx context.Context, updates []bigcommerce.ProductUpdate) (*bigcommerce.BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateProducts", ctx, updates)
	ret0, _ := ret[0].(*bigcommerce.BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateProducts indicates an expected call of BatchUpdateProducts.
func (mr *MockBigCommerceAPIMockRecorder) BatchUpdateProducts(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateProducts", reflect.TypeOf((*MockBigCommerceAPI)(nil).BatchUpdateProducts), ctx, updates)
}

// CreateCategory mocks base method.
func (m *MockBigCommerceAPI) CreateCategory(ctx context.Context, payload bigcommerce.CategoryCreate) ([]bigcommerce.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockBigCommerceAPIMockRecorder) CreateCategory(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateCategory), ctx, payload)
}

// CreateCategoryMetafield mocks base method.
func (m *MockBigCommerceAPI) CreateCategoryMetafield(ctx context.Context, categoryID int, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryMetafield", ctx, categoryID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategoryMetafield indicates an expected call of CreateCategoryMetafield.
func (mr *MockBigCommerceAPIMockRecorder) CreateCategoryMetafield(ctx, categoryID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryMetafield", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateCategoryMetafield), ctx, categoryID, mf)
}

// CreateProduct mocks base method.
func (m *MockBigCommerceAPI) CreateProduct(ctx context.Context, payload bigcommerce.ProductCreate) (*bigcommerce.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockBigCommerceAPIMockRecorder) CreateProduct(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateProduct), ctx, payload)
}

// CreateProductCustomField mocks base method.
func (m *MockBigCommerceAPI) CreateProductCustomField(ctx context.Context, productID int, payload bigcommerce.ProductCustomFieldCreate) (*bigcommerce.ProductCustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductCustomField", ctx, productID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductCustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductCustomField indicates an expected call of CreateProductCustomField.
func (mr *MockBigCommerceAPIMockRecorder) CreateProductCustomField(ctx, productID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductCustomField", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateProductCustomField), ctx, productID, payload)
}

// CreateProductImage mocks base method.
func (m *MockBigCommerceAPI) CreateProductImage(ctx context.Context, productID int, payload bigcommerce.ProductImageCreate) (*bigcommerce.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductImage", ctx, productID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductImage indicates an expected call of CreateProductImage.
func (mr *MockBigCommerceAPIMockRecorder) CreateProductImage(ctx, productID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductImage", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateProductImage), ctx, productID, payload)
}

// CreateProductModifier mocks base method.
func (m *MockBigCommerceAPI) CreateProductModifier(ctx context.Context, productID int, payload bigcommerce.ProductModifierCreate) (*bigcommerce.ProductModifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductModifier", ctx, productID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductModifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductModifier indicates an expected call of CreateProductModifier.
func (mr *MockBigCommerceAPIMockRecorder) CreateProductModifier(ctx, productID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductModifier", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateProductModifier), ctx, productID, payload)
}

// CreateProductOption mocks base method.
func (m *MockBigCommerceAPI) CreateProductOption(ctx context.Context, productID int, payload bigcommerce.ProductOptionCreate) (*bigcommerce.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductOption", ctx, productID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductOption indicates an expected call of CreateProductOption.
func (mr *MockBigCommerceAPIMockRecorder) CreateProductOption(ctx, productID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductOption", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateProductOption), ctx, productID, payload)
}

// CreateVariant mocks base method.
func (m *MockBigCommerceAPI) CreateVariant(ctx context.Context, productID int, payload bigcommerce.ProductVariantCreate) (*bigcommerce.ProductVariantFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariant", ctx, productID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductVariantFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVariant indicates an expected call of CreateVariant.
func (mr *MockBigCommerceAPIMockRecorder) CreateVariant(ctx, productID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariant", reflect.TypeOf((*MockBigCommerceAPI)(nil).CreateVariant), ctx, productID, payload)
}

// DeleteCategories mocks base method.
func (m *MockBigCommerceAPI) DeleteCategories(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategories", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategories indicates an expected call of DeleteCategories.
func (mr *MockBigCommerceAPIMockRecorder) DeleteCategories(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategories", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteCategories), ctx, ids)
}

// DeleteCategoryAssignments mocks base method.
func (m *MockBigCommerceAPI) DeleteCategoryAssignments(ctx context.Context, productID, categoryID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryAssignments", ctx, productID, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategoryAssignments indicates an expected call of DeleteCategoryAssignments.
func (mr *MockBigCommerceAPIMockRecorder) DeleteCategoryAssignments(ctx, productID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryAssignments", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteCategoryAssignments), ctx, productID, categoryID)
}

// DeleteCategoryMetafield mocks base method.
func (m *MockBigCommerceAPI) DeleteCategoryMetafield(ctx context.Context, categoryID, metafieldID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryMetafield", ctx, categoryID, metafieldID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategoryMetafield indicates an expected call of DeleteCategoryMetafield.
func (mr *MockBigCommerceAPIMockRecorder) DeleteCategoryMetafield(ctx, categoryID, metafieldID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryMetafield", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteCategoryMetafield), ctx, categoryID, metafieldID)
}

// DeleteProduct mocks base method.
func (m *MockBigCommerceAPI) DeleteProduct(ctx context.Context, productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProduct), ctx, productID)
}

// DeleteProductCustomField mocks base method.
func (m *MockBigCommerceAPI) DeleteProductCustomField(ctx context.Context, productID, fieldID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductCustomField", ctx, productID, fieldID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductCustomField indicates an expected call of DeleteProductCustomField.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProductCustomField(ctx, productID, fieldID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductCustomField", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProductCustomField), ctx, productID, fieldID)
}

// DeleteProductImage mocks base method.
func (m *MockBigCommerceAPI) DeleteProductImage(ctx context.Context, productID, imageID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImage", ctx, productID, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImage indicates an expected call of DeleteProductImage.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProductImage(ctx, productID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImage", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProductImage), ctx, productID, imageID)
}

// DeleteProductModifier mocks base method.
func (m *MockBigCommerceAPI) DeleteProductModifier(ctx context.Context, productID, modifierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductModifier", ctx, productID, modifierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductModifier indicates an expected call of DeleteProductModifier.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProductModifier(ctx, productID, modifierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductModifier", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProductModifier), ctx, productID, modifierID)
}

// DeleteProductOption mocks base method.
func (m *MockBigCommerceAPI) DeleteProductOption(ctx context.Context, productID, optionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductOption", ctx, productID, optionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductOption indicates an expected call of DeleteProductOption.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProductOption(ctx, productID, optionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductOption", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProductOption), ctx, productID, optionID)
}

// DeleteProducts mocks base method.
func (m *MockBigCommerceAPI) DeleteProducts(ctx context.Context, productIDs []int) ([]int, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProducts", ctx, productIDs)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// DeleteProducts indicates an expected call of DeleteProducts.
func (mr *MockBigCommerceAPIMockRecorder) DeleteProducts(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProducts", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteProducts), ctx, productIDs)
}

// DeleteVariant mocks base method.
func (m *MockBigCommerceAPI) DeleteVariant(ctx context.Context, productID, variantID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariant", ctx, productID, variantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVariant indicates an expected call of DeleteVariant.
func (mr *MockBigCommerceAPIMockRecorder) DeleteVariant(ctx, productID, variantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariant", reflect.TypeOf((*MockBigCommerceAPI)(nil).DeleteVariant), ctx, productID, variantID)
}

// GetCategory mocks base method.
func (m *MockBigCommerceAPI) GetCategory(ctx context.Context, categoryID int) (*bigcommerce.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, categoryID)
	ret0, _ := ret[0].(*bigcommerce.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockBigCommerceAPIMockRecorder) GetCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetCategory), ctx, categoryID)
}

// GetCategoriesByIDs mocks base method.
func (m *MockBigCommerceAPI) GetCategoriesByIDs(ctx context.Context, categoryIDs []int) ([]bigcommerce.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesByIDs", ctx, categoryIDs)
	ret0, _ := ret[0].([]bigcommerce.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByIDs indicates an expected call of GetCategoriesByIDs.
func (mr *MockBigCommerceAPIMockRecorder) GetCategoriesByIDs(ctx, categoryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByIDs", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetCategoriesByIDs), ctx, categoryIDs)
}

// GetDefaultTreeID mocks base method.
func (m *MockBigCommerceAPI) GetDefaultTreeID(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultTreeID", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultTreeID indicates an expected call of GetDefaultTreeID.
func (mr *MockBigCommerceAPIMockRecorder) GetDefaultTreeID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultTreeID", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetDefaultTreeID), ctx)
}

// GetProduct mocks base method.
func (m *MockBigCommerceAPI) GetProduct(ctx context.Context, productID int) (*bigcommerce.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(*bigcommerce.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockBigCommerceAPIMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetProduct), ctx, productID)
}

// GetProductsByIDs mocks base method.
func (m *MockBigCommerceAPI) GetProductsByIDs(ctx context.Context, productIDs []int) ([]bigcommerce.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByIDs", ctx, productIDs)
	ret0, _ := ret[0].([]bigcommerce.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByIDs indicates an expected call of GetProductsByIDs.
func (mr *MockBigCommerceAPIMockRecorder) GetProductsByIDs(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByIDs", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetProductsByIDs), ctx, productIDs)
}

// GetVariant mocks base method.
func (m *MockBigCommerceAPI) GetVariant(ctx context.Context, productID, variantID int) (*bigcommerce.ProductVariantFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariant", ctx, productID, variantID)
	ret0, _ := ret[0].(*bigcommerce.ProductVariantFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVariant indicates an expected call of GetVariant.
func (mr *MockBigCommerceAPIMockRecorder) GetVariant(ctx, productID, variantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariant", reflect.TypeOf((*MockBigCommerceAPI)(nil).GetVariant), ctx, productID, variantID)
}

// ListCategoryMetafields mocks base method.
func (m *MockBigCommerceAPI) ListCategoryMetafields(ctx context.Context, categoryID int) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoryMetafields", ctx, categoryID)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoryMetafields indicates an expected call of ListCategoryMetafields.
func (mr *MockBigCommerceAPIMockRecorder) ListCategoryMetafields(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoryMetafields", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListCategoryMetafields), ctx, categoryID)
}

// ListProductCustomFields mocks base method.
func (m *MockBigCommerceAPI) ListProductCustomFields(ctx context.Context, productID int) ([]bigcommerce.ProductCustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductCustomFields", ctx, productID)
	ret0, _ := ret[0].([]bigcommerce.ProductCustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductCustomFields indicates an expected call of ListProductCustomFields.
func (mr *MockBigCommerceAPIMockRecorder) ListProductCustomFields(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductCustomFields", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListProductCustomFields), ctx, productID)
}

// ListProductImages mocks base method.
func (m *MockBigCommerceAPI) ListProductImages(ctx context.Context, productID int) ([]bigcommerce.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductImages", ctx, productID)
	ret0, _ := ret[0].([]bigcommerce.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductImages indicates an expected call of ListProductImages.
func (mr *MockBigCommerceAPIMockRecorder) ListProductImages(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductImages", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListProductImages), ctx, productID)
}

// ListProductModifiers mocks base method.
func (m *MockBigCommerceAPI) ListProductModifiers(ctx context.Context, productID int) ([]bigcommerce.ProductModifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductModifiers", ctx, productID)
	ret0, _ := ret[0].([]bigcommerce.ProductModifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductModifiers indicates an expected call of ListProductModifiers.
func (mr *MockBigCommerceAPIMockRecorder) ListProductModifiers(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductModifiers", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListProductModifiers), ctx, productID)
}

// ListProductOptions mocks base method.
func (m *MockBigCommerceAPI) ListProductOptions(ctx context.Context, productID int) ([]bigcommerce.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductOptions", ctx, productID)
	ret0, _ := ret[0].([]bigcommerce.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductOptions indicates an expected call of ListProductOptions.
func (mr *MockBigCommerceAPIMockRecorder) ListProductOptions(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductOptions", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListProductOptions), ctx, productID)
}

// ListProductsByCategory mocks base method.
func (m *MockBigCommerceAPI) ListProductsByCategory(ctx context.Context, categoryID int, opts bigcommerce.ProductListOptions) ([]bigcommerce.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByCategory", ctx, categoryID, opts)
	ret0, _ := ret[0].([]bigcommerce.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByCategory indicates an expected call of ListProductsByCategory.
func (mr *MockBigCommerceAPIMockRecorder) ListProductsByCategory(ctx, categoryID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByCategory", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListProductsByCategory), ctx, categoryID, opts)
}

// ListVariantsByProductIDs mocks base method.
func (m *MockBigCommerceAPI) ListVariantsByProductIDs(ctx context.Context, productIDs []int) ([]bigcommerce.Variant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantsByProductIDs", ctx, productIDs)
	ret0, _ := ret[0].([]bigcommerce.Variant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantsByProductIDs indicates an expected call of ListVariantsByProductIDs.
func (mr *MockBigCommerceAPIMockRecorder) ListVariantsByProductIDs(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantsByProductIDs", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListVariantsByProductIDs), ctx, productIDs)
}

// ListVariantsForProduct mocks base method.
func (m *MockBigCommerceAPI) ListVariantsForProduct(ctx context.Context, productID int) ([]bigcommerce.Variant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantsForProduct", ctx, productID)
	ret0, _ := ret[0].([]bigcommerce.Variant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantsForProduct indicates an expected call of ListVariantsForProduct.
func (mr *MockBigCommerceAPIMockRecorder) ListVariantsForProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantsForProduct", reflect.TypeOf((*MockBigCommerceAPI)(nil).ListVariantsForProduct), ctx, productID)
}

// SearchCategories mocks base method.
func (m *MockBigCommerceAPI) SearchCategories(ctx context.Context, params map[string]string) ([]bigcommerce.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCategories", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCategories indicates an expected call of SearchCategories.
func (mr *MockBigCommerceAPIMockRecorder) SearchCategories(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCategories", reflect.TypeOf((*MockBigCommerceAPI)(nil).SearchCategories), ctx, params)
}

// SearchProducts mocks base method.
func (m *MockBigCommerceAPI) SearchProducts(ctx context.Context, params map[string]string) ([]bigcommerce.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockBigCommerceAPIMockRecorder) SearchProducts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockBigCommerceAPI)(nil).SearchProducts), ctx, params)
}

// UpdateCategoryMetafield mocks base method.
func (m *MockBigCommerceAPI) UpdateCategoryMetafield(ctx context.Context, categoryID, metafieldID int, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategoryMetafield", ctx, categoryID, metafieldID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategoryMetafield indicates an expected call of UpdateCategoryMetafield.
func (mr *MockBigCommerceAPIMockRecorder) UpdateCategoryMetafield(ctx, categoryID, metafieldID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategoryMetafield", reflect.TypeOf((*MockBigCommerceAPI)(nil).UpdateCategoryMetafield), ctx, categoryID, metafieldID, mf)
}

// UpdateProductCustomField mocks base method.
func (m *MockBigCommerceAPI) UpdateProductCustomField(ctx context.Context, productID, fieldID int, payload bigcommerce.ProductCustomFieldCreate) (*bigcommerce.ProductCustomField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductCustomField", ctx, productID, fieldID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductCustomField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProductCustomField indicates an expected call of UpdateProductCustomField.
func (mr *MockBigCommerceAPIMockRecorder) UpdateProductCustomField(ctx, productID, fieldID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductCustomField", reflect.TypeOf((*MockBigCommerceAPI)(nil).UpdateProductCustomField), ctx, productID, fieldID, payload)
}

// UpdateProductOption mocks base method.
func (m *MockBigCommerceAPI) UpdateProductOption(ctx context.Context, productID, optionID int, payload bigcommerce.ProductOptionUpdate) (*bigcommerce.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductOption", ctx, productID, optionID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProductOption indicates an expected call of UpdateProductOption.
func (mr *MockBigCommerceAPIMockRecorder) UpdateProductOption(ctx, productID, optionID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductOption", reflect.TypeOf((*MockBigCommerceAPI)(nil).UpdateProductOption), ctx, productID, optionID, payload)
}

// UpdateVariant mocks base method.
func (m *MockBigCommerceAPI) UpdateVariant(ctx context.Context, productID, variantID int, payload bigcommerce.ProductVariantUpdate) (*bigcommerce.ProductVariantFull, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariant", ctx, productID, variantID, payload)
	ret0, _ := ret[0].(*bigcommerce.ProductVariantFull)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVariant indicates an expected call of UpdateVariant.
func (mr *MockBigCommerceAPIMockRecorder) UpdateVariant(ctx, productID, variantID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariant", reflect.TypeOf((*MockBigCommerceAPI)(nil).UpdateVariant), ctx, productID, variantID, payload)
}

// UpsertCategoryAssignments mocks base method.
func (m *MockBigCommerceAPI) UpsertCategoryAssignments(ctx context.Context, assignments []bigcommerce.CategoryAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCategoryAssignments", ctx, assignments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCategoryAssignments indicates an expected call of UpsertCategoryAssignments.
func (mr *MockBigCommerceAPIMockRecorder) UpsertCategoryAssignments(ctx, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCategoryAssignments", reflect.TypeOf((*MockBigCommerceAPI)(nil).UpsertCategoryAssignments), ctx, assignments)
}
