// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/b2b/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/tools/b2b/interfaces.go -destination=internal/tools/b2b/mock_bc_test.go -package=b2b_test
//

// Package b2b_test is a generated GoMock package.
package b2b_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockB2BCompanyAPI is a mock of B2BCompanyAPI interface.
type MockB2BCompanyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockB2BCompanyAPIMockRecorder
	isgomock struct{}
}

// MockB2BCompanyAPIMockRecorder is the mock recorder for MockB2BCompanyAPI.
type MockB2BCompanyAPIMockRecorder struct {
	mock *MockB2BCompanyAPI
}

// NewMockB2BCompanyAPI creates a new mock instance.
func NewMockB2BCompanyAPI(ctrl *gomock.Controller) *MockB2BCompanyAPI {
	mock := &MockB2BCompanyAPI{ctrl: ctrl}
	mock.recorder = &MockB2BCompanyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockB2BCompanyAPI) EXPECT() *MockB2BCompanyAPIMockRecorder {
	return m.recorder
}

// AddB2BCompanyAttachment mocks base method.
func (m *MockB2BCompanyAPI) AddB2BCompanyAttachment(ctx context.Context, companyID int, fileName string, data []byte) (*bigcommerce.B2BAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddB2BCompanyAttachment", ctx, companyID, fileName, data)
	ret0, _ := ret[0].(*bigcommerce.B2BAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddB2BCompanyAttachment indicates an expected call of AddB2BCompanyAttachment.
func (mr *MockB2BCompanyAPIMockRecorder) AddB2BCompanyAttachment(ctx, companyID, fileName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddB2BCompanyAttachment", reflect.TypeOf((*MockB2BCompanyAPI)(nil).AddB2BCompanyAttachment), ctx, companyID, fileName, data)
}

// AssignB2BQuoteToOrder mocks base method.
func (m *MockB2BCompanyAPI) AssignB2BQuoteToOrder(ctx context.Context, quoteID, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignB2BQuoteToOrder", ctx, quoteID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignB2BQuoteToOrder indicates an expected call of AssignB2BQuoteToOrder.
func (mr *MockB2BCompanyAPIMockRecorder) AssignB2BQuoteToOrder(ctx, quoteID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignB2BQuoteToOrder", reflect.TypeOf((*MockB2BCompanyAPI)(nil).AssignB2BQuoteToOrder), ctx, quoteID, orderID)
}

// AssignCustomerOrdersToCompany mocks base method.
func (m *MockB2BCompanyAPI) AssignCustomerOrdersToCompany(ctx context.Context, customerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignCustomerOrdersToCompany", ctx, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignCustomerOrdersToCompany indicates an expected call of AssignCustomerOrdersToCompany.
func (mr *MockB2BCompanyAPIMockRecorder) AssignCustomerOrdersToCompany(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignCustomerOrdersToCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).AssignCustomerOrdersToCompany), ctx, customerID)
}

// AttachB2BCompanyParent mocks base method.
func (m *MockB2BCompanyAPI) AttachB2BCompanyParent(ctx context.Context, companyID, parentCompanyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachB2BCompanyParent", ctx, companyID, parentCompanyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachB2BCompanyParent indicates an expected call of AttachB2BCompanyParent.
func (mr *MockB2BCompanyAPIMockRecorder) AttachB2BCompanyParent(ctx, companyID, parentCompanyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachB2BCompanyParent", reflect.TypeOf((*MockB2BCompanyAPI)(nil).AttachB2BCompanyParent), ctx, companyID, parentCompanyID)
}

// BulkCreateB2BSuperAdmins mocks base method.
func (m *MockB2BCompanyAPI) BulkCreateB2BSuperAdmins(ctx context.Context, payloads []bigcommerce.B2BSuperAdminCreate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateB2BSuperAdmins", ctx, payloads)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkCreateB2BSuperAdmins indicates an expected call of BulkCreateB2BSuperAdmins.
func (mr *MockB2BCompanyAPIMockRecorder) BulkCreateB2BSuperAdmins(ctx, payloads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateB2BSuperAdmins", reflect.TypeOf((*MockB2BCompanyAPI)(nil).BulkCreateB2BSuperAdmins), ctx, payloads)
}

// BulkCreateB2BUsers mocks base method.
func (m *MockB2BCompanyAPI) BulkCreateB2BUsers(ctx context.Context, payloads []bigcommerce.B2BUserCreate) ([]bigcommerce.B2BNewUserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateB2BUsers", ctx, payloads)
	ret0, _ := ret[0].([]bigcommerce.B2BNewUserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkCreateB2BUsers indicates an expected call of BulkCreateB2BUsers.
func (mr *MockB2BCompanyAPIMockRecorder) BulkCreateB2BUsers(ctx, payloads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateB2BUsers", reflect.TypeOf((*MockB2BCompanyAPI)(nil).BulkCreateB2BUsers), ctx, payloads)
}

// CreateB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BAddress(ctx context.Context, payload bigcommerce.B2BAddressCreate) (*bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BAddress", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BAddress indicates an expected call of CreateB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BAddress(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BAddress), ctx, payload)
}

// CreateB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BCompany(ctx context.Context, payload bigcommerce.B2BCompanyCreate) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BCompany", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BCompany indicates an expected call of CreateB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BCompany(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BCompany), ctx, payload)
}

// CreateB2BPermission mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BPermission(ctx context.Context, payload bigcommerce.B2BPermissionCreate) (*bigcommerce.B2BPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BPermission", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BPermission indicates an expected call of CreateB2BPermission.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BPermission(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BPermission", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BPermission), ctx, payload)
}

// CreateB2BQuote mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BQuote(ctx context.Context, body map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BQuote", ctx, body)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BQuote indicates an expected call of CreateB2BQuote.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BQuote(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BQuote", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BQuote), ctx, body)
}

// CreateB2BRole mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BRole(ctx context.Context, payload bigcommerce.B2BRoleCreate) (*bigcommerce.B2BRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BRole", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BRole indicates an expected call of CreateB2BRole.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BRole(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BRole", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BRole), ctx, payload)
}

// CreateB2BShoppingList mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BShoppingList(ctx context.Context, payload bigcommerce.B2BShoppingListCreate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BShoppingList", ctx, payload)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BShoppingList indicates an expected call of CreateB2BShoppingList.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BShoppingList(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BShoppingList", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BShoppingList), ctx, payload)
}

// CreateB2BSuperAdmin mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BSuperAdmin(ctx context.Context, payload bigcommerce.B2BSuperAdminCreate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BSuperAdmin", ctx, payload)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BSuperAdmin indicates an expected call of CreateB2BSuperAdmin.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BSuperAdmin(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BSuperAdmin", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BSuperAdmin), ctx, payload)
}

// CreateB2BUser mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BUser(ctx context.Context, payload bigcommerce.B2BUserCreate) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BUser", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BUser indicates an expected call of CreateB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BUser(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BUser), ctx, payload)
}

// DeleteB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BAddress(ctx context.Context, addressID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BAddress", ctx, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BAddress indicates an expected call of DeleteB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BAddress(ctx, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BAddress), ctx, addressID)
}

// DeleteB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BCompany(ctx context.Context, companyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BCompany", ctx, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BCompany indicates an expected call of DeleteB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BCompany), ctx, companyID)
}

// DeleteB2BCompanyAttachment mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BCompanyAttachment(ctx context.Context, companyID int, attachmentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BCompanyAttachment", ctx, companyID, attachmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BCompanyAttachment indicates an expected call of DeleteB2BCompanyAttachment.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BCompanyAttachment(ctx, companyID, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BCompanyAttachment", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BCompanyAttachment), ctx, companyID, attachmentID)
}

// DeleteB2BCompanySubsidiary mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BCompanySubsidiary(ctx context.Context, companyID, childCompanyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BCompanySubsidiary", ctx, companyID, childCompanyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BCompanySubsidiary indicates an expected call of DeleteB2BCompanySubsidiary.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BCompanySubsidiary(ctx, companyID, childCompanyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BCompanySubsidiary", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BCompanySubsidiary), ctx, companyID, childCompanyID)
}

// DeleteB2BPermission mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BPermission(ctx context.Context, permissionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BPermission", ctx, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BPermission indicates an expected call of DeleteB2BPermission.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BPermission(ctx, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BPermission", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BPermission), ctx, permissionID)
}

// DeleteB2BQuote mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BQuote(ctx context.Context, quoteID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BQuote", ctx, quoteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BQuote indicates an expected call of DeleteB2BQuote.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BQuote(ctx, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BQuote", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BQuote), ctx, quoteID)
}

// DeleteB2BRole mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BRole(ctx context.Context, roleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BRole", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BRole indicates an expected call of DeleteB2BRole.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BRole(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BRole", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BRole), ctx, roleID)
}

// DeleteB2BShoppingList mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BShoppingList(ctx context.Context, shoppingListID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BShoppingList", ctx, shoppingListID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BShoppingList indicates an expected call of DeleteB2BShoppingList.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BShoppingList(ctx, shoppingListID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BShoppingList", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BShoppingList), ctx, shoppingListID, userID)
}

// DeleteB2BShoppingListItem mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BShoppingListItem(ctx context.Context, shoppingListID, itemID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BShoppingListItem", ctx, shoppingListID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BShoppingListItem indicates an expected call of DeleteB2BShoppingListItem.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BShoppingListItem(ctx, shoppingListID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BShoppingListItem", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BShoppingListItem), ctx, shoppingListID, itemID)
}

// DeleteB2BUser mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BUser indicates an expected call of DeleteB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BUser), ctx, userID)
}

// DownloadB2BInvoicePDF mocks base method.
func (m *MockB2BCompanyAPI) DownloadB2BInvoicePDF(ctx context.Context, invoiceID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadB2BInvoicePDF", ctx, invoiceID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadB2BInvoicePDF indicates an expected call of DownloadB2BInvoicePDF.
func (mr *MockB2BCompanyAPIMockRecorder) DownloadB2BInvoicePDF(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadB2BInvoicePDF", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DownloadB2BInvoicePDF), ctx, invoiceID)
}

// ExportB2BQuotePDF mocks base method.
func (m *MockB2BCompanyAPI) ExportB2BQuotePDF(ctx context.Context, quoteID int, currency map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportB2BQuotePDF", ctx, quoteID, currency)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportB2BQuotePDF indicates an expected call of ExportB2BQuotePDF.
func (mr *MockB2BCompanyAPIMockRecorder) ExportB2BQuotePDF(ctx, quoteID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportB2BQuotePDF", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ExportB2BQuotePDF), ctx, quoteID, currency)
}

// GenerateB2BQuoteCheckout mocks base method.
func (m *MockB2BCompanyAPI) GenerateB2BQuoteCheckout(ctx context.Context, quoteID int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateB2BQuoteCheckout", ctx, quoteID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateB2BQuoteCheckout indicates an expected call of GenerateB2BQuoteCheckout.
func (mr *MockB2BCompanyAPIMockRecorder) GenerateB2BQuoteCheckout(ctx, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateB2BQuoteCheckout", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GenerateB2BQuoteCheckout), ctx, quoteID)
}

// GetB2BChannel mocks base method.
func (m *MockB2BCompanyAPI) GetB2BChannel(ctx context.Context, channelID int) (*bigcommerce.B2BChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BChannel", ctx, channelID)
	ret0, _ := ret[0].(*bigcommerce.B2BChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BChannel indicates an expected call of GetB2BChannel.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BChannel(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BChannel", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BChannel), ctx, channelID)
}

// GetB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) GetB2BCompany(ctx context.Context, companyID int) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BCompany", ctx, companyID)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BCompany indicates an expected call of GetB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BCompany), ctx, companyID)
}

// GetB2BCompanyCredit mocks base method.
func (m *MockB2BCompanyAPI) GetB2BCompanyCredit(ctx context.Context, companyID int) (*bigcommerce.B2BCompanyCredit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BCompanyCredit", ctx, companyID)
	ret0, _ := ret[0].(*bigcommerce.B2BCompanyCredit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BCompanyCredit indicates an expected call of GetB2BCompanyCredit.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BCompanyCredit(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BCompanyCredit", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BCompanyCredit), ctx, companyID)
}

// GetB2BCompanyPaymentTerms mocks base method.
func (m *MockB2BCompanyAPI) GetB2BCompanyPaymentTerms(ctx context.Context, companyID int) (*bigcommerce.B2BPaymentTerms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BCompanyPaymentTerms", ctx, companyID)
	ret0, _ := ret[0].(*bigcommerce.B2BPaymentTerms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BCompanyPaymentTerms indicates an expected call of GetB2BCompanyPaymentTerms.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BCompanyPaymentTerms(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BCompanyPaymentTerms", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BCompanyPaymentTerms), ctx, companyID)
}

// GetB2BInvoice mocks base method.
func (m *MockB2BCompanyAPI) GetB2BInvoice(ctx context.Context, invoiceID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BInvoice", ctx, invoiceID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BInvoice indicates an expected call of GetB2BInvoice.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BInvoice(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BInvoice", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BInvoice), ctx, invoiceID)
}

// GetB2BOrder mocks base method.
func (m *MockB2BCompanyAPI) GetB2BOrder(ctx context.Context, bcOrderID int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BOrder", ctx, bcOrderID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BOrder indicates an expected call of GetB2BOrder.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BOrder(ctx, bcOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BOrder", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BOrder), ctx, bcOrderID)
}

// GetB2BQuote mocks base method.
func (m *MockB2BCompanyAPI) GetB2BQuote(ctx context.Context, quoteID int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BQuote", ctx, quoteID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BQuote indicates an expected call of GetB2BQuote.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BQuote(ctx, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BQuote", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BQuote), ctx, quoteID)
}

// GetB2BReceipt mocks base method.
func (m *MockB2BCompanyAPI) GetB2BReceipt(ctx context.Context, receiptID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BReceipt", ctx, receiptID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BReceipt indicates an expected call of GetB2BReceipt.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BReceipt(ctx, receiptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BReceipt", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BReceipt), ctx, receiptID)
}

// GetB2BReceiptLine mocks base method.
func (m *MockB2BCompanyAPI) GetB2BReceiptLine(ctx context.Context, receiptID, lineID string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BReceiptLine", ctx, receiptID, lineID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BReceiptLine indicates an expected call of GetB2BReceiptLine.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BReceiptLine(ctx, receiptID, lineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BReceiptLine", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BReceiptLine), ctx, receiptID, lineID)
}

// GetB2BRole mocks base method.
func (m *MockB2BCompanyAPI) GetB2BRole(ctx context.Context, roleID int) (*bigcommerce.B2BRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BRole", ctx, roleID)
	ret0, _ := ret[0].(*bigcommerce.B2BRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BRole indicates an expected call of GetB2BRole.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BRole(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BRole", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BRole), ctx, roleID)
}

// GetB2BSalesStaff mocks base method.
func (m *MockB2BCompanyAPI) GetB2BSalesStaff(ctx context.Context, salesStaffID int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BSalesStaff", ctx, salesStaffID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BSalesStaff indicates an expected call of GetB2BSalesStaff.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BSalesStaff(ctx, salesStaffID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BSalesStaff", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BSalesStaff), ctx, salesStaffID)
}

// GetB2BShoppingList mocks base method.
func (m *MockB2BCompanyAPI) GetB2BShoppingList(ctx context.Context, shoppingListID int, params string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BShoppingList", ctx, shoppingListID, params)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BShoppingList indicates an expected call of GetB2BShoppingList.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BShoppingList(ctx, shoppingListID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BShoppingList", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BShoppingList), ctx, shoppingListID, params)
}

// GetB2BSuperAdmin mocks base method.
func (m *MockB2BCompanyAPI) GetB2BSuperAdmin(ctx context.Context, superAdminID int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BSuperAdmin", ctx, superAdminID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BSuperAdmin indicates an expected call of GetB2BSuperAdmin.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BSuperAdmin(ctx, superAdminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BSuperAdmin", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BSuperAdmin), ctx, superAdminID)
}

// GetB2BSuperAdminCompanies mocks base method.
func (m *MockB2BCompanyAPI) GetB2BSuperAdminCompanies(ctx context.Context, superAdminID int, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BSuperAdminCompanies", ctx, superAdminID, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BSuperAdminCompanies indicates an expected call of GetB2BSuperAdminCompanies.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BSuperAdminCompanies(ctx, superAdminID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BSuperAdminCompanies", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BSuperAdminCompanies), ctx, superAdminID, params)
}

// GetB2BUser mocks base method.
func (m *MockB2BCompanyAPI) GetB2BUser(ctx context.Context, userID int) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BUser", ctx, userID)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BUser indicates an expected call of GetB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BUser), ctx, userID)
}

// GetB2BUserByCustomerID mocks base method.
func (m *MockB2BCompanyAPI) GetB2BUserByCustomerID(ctx context.Context, customerID int) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BUserByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BUserByCustomerID indicates an expected call of GetB2BUserByCustomerID.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BUserByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BUserByCustomerID", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BUserByCustomerID), ctx, customerID)
}

// ListB2BActivePaymentMethods mocks base method.
func (m *MockB2BCompanyAPI) ListB2BActivePaymentMethods(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BActivePaymentMethods", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BActivePaymentMethods indicates an expected call of ListB2BActivePaymentMethods.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BActivePaymentMethods(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BActivePaymentMethods", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BActivePaymentMethods), ctx, params)
}

// ListB2BAddresses mocks base method.
func (m *MockB2BCompanyAPI) ListB2BAddresses(ctx context.Context, params string) ([]bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BAddresses", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BAddresses indicates an expected call of ListB2BAddresses.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BAddresses(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BAddresses", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BAddresses), ctx, params)
}

// ListB2BChannels mocks base method.
func (m *MockB2BCompanyAPI) ListB2BChannels(ctx context.Context) ([]bigcommerce.B2BChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BChannels", ctx)
	ret0, _ := ret[0].([]bigcommerce.B2BChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BChannels indicates an expected call of ListB2BChannels.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BChannels", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BChannels), ctx)
}

// ListB2BCompanies mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanies(ctx context.Context, params string) ([]bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanies", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanies indicates an expected call of ListB2BCompanies.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanies(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanies", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanies), ctx, params)
}

// ListB2BCompanyAttachments mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanyAttachments(ctx context.Context, companyID int) ([]bigcommerce.B2BAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanyAttachments", ctx, companyID)
	ret0, _ := ret[0].([]bigcommerce.B2BAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanyAttachments indicates an expected call of ListB2BCompanyAttachments.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanyAttachments(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanyAttachments", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanyAttachments), ctx, companyID)
}

// ListB2BCompanyExtraFields mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanyExtraFields(ctx context.Context, params string) ([]bigcommerce.B2BExtraFieldDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanyExtraFields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BExtraFieldDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanyExtraFields indicates an expected call of ListB2BCompanyExtraFields.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanyExtraFields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanyExtraFields", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanyExtraFields), ctx, params)
}

// ListB2BCompanyHierarchy mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanyHierarchy(ctx context.Context, companyID int, params string) ([]bigcommerce.B2BHierarchyNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanyHierarchy", ctx, companyID, params)
	ret0, _ := ret[0].([]bigcommerce.B2BHierarchyNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanyHierarchy indicates an expected call of ListB2BCompanyHierarchy.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanyHierarchy(ctx, companyID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanyHierarchy", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanyHierarchy), ctx, companyID, params)
}

// ListB2BCompanyPaymentMethods mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanyPaymentMethods(ctx context.Context, companyID int) ([]bigcommerce.B2BCompanyPaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanyPaymentMethods", ctx, companyID)
	ret0, _ := ret[0].([]bigcommerce.B2BCompanyPaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanyPaymentMethods indicates an expected call of ListB2BCompanyPaymentMethods.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanyPaymentMethods(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanyPaymentMethods", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanyPaymentMethods), ctx, companyID)
}

// ListB2BCompanySubsidiaries mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanySubsidiaries(ctx context.Context, companyID int, params string) ([]bigcommerce.B2BHierarchyNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanySubsidiaries", ctx, companyID, params)
	ret0, _ := ret[0].([]bigcommerce.B2BHierarchyNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanySubsidiaries indicates an expected call of ListB2BCompanySubsidiaries.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanySubsidiaries(ctx, companyID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanySubsidiaries", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanySubsidiaries), ctx, companyID, params)
}

// ListB2BCompanySuperAdmins mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanySuperAdmins(ctx context.Context, companyID int, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanySuperAdmins", ctx, companyID, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanySuperAdmins indicates an expected call of ListB2BCompanySuperAdmins.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanySuperAdmins(ctx, companyID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanySuperAdmins", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanySuperAdmins), ctx, companyID, params)
}

// ListB2BInvoiceExtraFields mocks base method.
func (m *MockB2BCompanyAPI) ListB2BInvoiceExtraFields(ctx context.Context, params string) ([]bigcommerce.B2BExtraFieldDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BInvoiceExtraFields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BExtraFieldDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BInvoiceExtraFields indicates an expected call of ListB2BInvoiceExtraFields.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BInvoiceExtraFields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BInvoiceExtraFields", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BInvoiceExtraFields), ctx, params)
}

// ListB2BInvoices mocks base method.
func (m *MockB2BCompanyAPI) ListB2BInvoices(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BInvoices", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BInvoices indicates an expected call of ListB2BInvoices.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BInvoices(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BInvoices", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BInvoices), ctx, params)
}

// ListB2BLinesOfReceipt mocks base method.
func (m *MockB2BCompanyAPI) ListB2BLinesOfReceipt(ctx context.Context, receiptID, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BLinesOfReceipt", ctx, receiptID, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BLinesOfReceipt indicates an expected call of ListB2BLinesOfReceipt.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BLinesOfReceipt(ctx, receiptID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BLinesOfReceipt", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BLinesOfReceipt), ctx, receiptID, params)
}

// ListB2BOrderExtraFields mocks base method.
func (m *MockB2BCompanyAPI) ListB2BOrderExtraFields(ctx context.Context, params string) ([]bigcommerce.B2BExtraFieldDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BOrderExtraFields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BExtraFieldDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BOrderExtraFields indicates an expected call of ListB2BOrderExtraFields.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BOrderExtraFields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BOrderExtraFields", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BOrderExtraFields), ctx, params)
}

// ListB2BPaymentMethods mocks base method.
func (m *MockB2BCompanyAPI) ListB2BPaymentMethods(ctx context.Context) ([]bigcommerce.B2BPaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BPaymentMethods", ctx)
	ret0, _ := ret[0].([]bigcommerce.B2BPaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BPaymentMethods indicates an expected call of ListB2BPaymentMethods.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BPaymentMethods(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BPaymentMethods", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BPaymentMethods), ctx)
}

// ListB2BPermissions mocks base method.
func (m *MockB2BCompanyAPI) ListB2BPermissions(ctx context.Context, params string) ([]bigcommerce.B2BPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BPermissions", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BPermissions indicates an expected call of ListB2BPermissions.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BPermissions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BPermissions", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BPermissions), ctx, params)
}

// ListB2BQuoteCustomShippingMethods mocks base method.
func (m *MockB2BCompanyAPI) ListB2BQuoteCustomShippingMethods(ctx context.Context) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BQuoteCustomShippingMethods", ctx)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BQuoteCustomShippingMethods indicates an expected call of ListB2BQuoteCustomShippingMethods.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BQuoteCustomShippingMethods(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BQuoteCustomShippingMethods", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BQuoteCustomShippingMethods), ctx)
}

// ListB2BQuoteExtraFields mocks base method.
func (m *MockB2BCompanyAPI) ListB2BQuoteExtraFields(ctx context.Context, params string) ([]bigcommerce.B2BExtraFieldDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BQuoteExtraFields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BExtraFieldDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BQuoteExtraFields indicates an expected call of ListB2BQuoteExtraFields.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BQuoteExtraFields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BQuoteExtraFields", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BQuoteExtraFields), ctx, params)
}

// ListB2BQuoteShippingRates mocks base method.
func (m *MockB2BCompanyAPI) ListB2BQuoteShippingRates(ctx context.Context, quoteID int) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BQuoteShippingRates", ctx, quoteID)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BQuoteShippingRates indicates an expected call of ListB2BQuoteShippingRates.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BQuoteShippingRates(ctx, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BQuoteShippingRates", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BQuoteShippingRates), ctx, quoteID)
}

// ListB2BQuotes mocks base method.
func (m *MockB2BCompanyAPI) ListB2BQuotes(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BQuotes", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BQuotes indicates an expected call of ListB2BQuotes.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BQuotes(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BQuotes", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BQuotes), ctx, params)
}

// ListB2BReceiptLines mocks base method.
func (m *MockB2BCompanyAPI) ListB2BReceiptLines(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BReceiptLines", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BReceiptLines indicates an expected call of ListB2BReceiptLines.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BReceiptLines(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BReceiptLines", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BReceiptLines), ctx, params)
}

// ListB2BReceipts mocks base method.
func (m *MockB2BCompanyAPI) ListB2BReceipts(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BReceipts", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BReceipts indicates an expected call of ListB2BReceipts.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BReceipts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BReceipts", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BReceipts), ctx, params)
}

// ListB2BRoles mocks base method.
func (m *MockB2BCompanyAPI) ListB2BRoles(ctx context.Context, params string) ([]bigcommerce.B2BRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BRoles", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BRoles indicates an expected call of ListB2BRoles.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BRoles(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BRoles", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BRoles), ctx, params)
}

// ListB2BSalesStaff mocks base method.
func (m *MockB2BCompanyAPI) ListB2BSalesStaff(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BSalesStaff", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BSalesStaff indicates an expected call of ListB2BSalesStaff.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BSalesStaff(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BSalesStaff", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BSalesStaff), ctx, params)
}

// ListB2BShoppingLists mocks base method.
func (m *MockB2BCompanyAPI) ListB2BShoppingLists(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BShoppingLists", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BShoppingLists indicates an expected call of ListB2BShoppingLists.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BShoppingLists(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BShoppingLists", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BShoppingLists), ctx, params)
}

// ListB2BSuperAdminCompaniesOverview mocks base method.
func (m *MockB2BCompanyAPI) ListB2BSuperAdminCompaniesOverview(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BSuperAdminCompaniesOverview", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BSuperAdminCompaniesOverview indicates an expected call of ListB2BSuperAdminCompaniesOverview.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BSuperAdminCompaniesOverview(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BSuperAdminCompaniesOverview", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BSuperAdminCompaniesOverview), ctx, params)
}

// ListB2BSuperAdmins mocks base method.
func (m *MockB2BCompanyAPI) ListB2BSuperAdmins(ctx context.Context, params string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BSuperAdmins", ctx, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BSuperAdmins indicates an expected call of ListB2BSuperAdmins.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BSuperAdmins(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BSuperAdmins", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BSuperAdmins), ctx, params)
}

// ListB2BUserExtraFields mocks base method.
func (m *MockB2BCompanyAPI) ListB2BUserExtraFields(ctx context.Context, params string) ([]bigcommerce.B2BExtraFieldDef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BUserExtraFields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BExtraFieldDef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BUserExtraFields indicates an expected call of ListB2BUserExtraFields.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BUserExtraFields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BUserExtraFields", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BUserExtraFields), ctx, params)
}

// ListB2BUsers mocks base method.
func (m *MockB2BCompanyAPI) ListB2BUsers(ctx context.Context, params string) ([]bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BUsers", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BUsers indicates an expected call of ListB2BUsers.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BUsers", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BUsers), ctx, params)
}

// ReassignOrdersToCompany mocks base method.
func (m *MockB2BCompanyAPI) ReassignOrdersToCompany(ctx context.Context, customerID, bcGroupID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignOrdersToCompany", ctx, customerID, bcGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignOrdersToCompany indicates an expected call of ReassignOrdersToCompany.
func (mr *MockB2BCompanyAPIMockRecorder) ReassignOrdersToCompany(ctx, customerID, bcGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignOrdersToCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ReassignOrdersToCompany), ctx, customerID, bcGroupID)
}

// RemoveB2BQuoteShippingRate mocks base method.
func (m *MockB2BCompanyAPI) RemoveB2BQuoteShippingRate(ctx context.Context, quoteID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveB2BQuoteShippingRate", ctx, quoteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveB2BQuoteShippingRate indicates an expected call of RemoveB2BQuoteShippingRate.
func (mr *MockB2BCompanyAPIMockRecorder) RemoveB2BQuoteShippingRate(ctx, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveB2BQuoteShippingRate", reflect.TypeOf((*MockB2BCompanyAPI)(nil).RemoveB2BQuoteShippingRate), ctx, quoteID)
}

// SelectB2BQuoteShippingRate mocks base method.
func (m *MockB2BCompanyAPI) SelectB2BQuoteShippingRate(ctx context.Context, quoteID int, shippingMethodID, customName string, customCost float64, hasCustomCost bool) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectB2BQuoteShippingRate", ctx, quoteID, shippingMethodID, customName, customCost, hasCustomCost)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectB2BQuoteShippingRate indicates an expected call of SelectB2BQuoteShippingRate.
func (mr *MockB2BCompanyAPIMockRecorder) SelectB2BQuoteShippingRate(ctx, quoteID, shippingMethodID, customName, customCost, hasCustomCost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectB2BQuoteShippingRate", reflect.TypeOf((*MockB2BCompanyAPI)(nil).SelectB2BQuoteShippingRate), ctx, quoteID, shippingMethodID, customName, customCost, hasCustomCost)
}

// SetB2BCompanyStatus mocks base method.
func (m *MockB2BCompanyAPI) SetB2BCompanyStatus(ctx context.Context, companyID int, action string) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetB2BCompanyStatus", ctx, companyID, action)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetB2BCompanyStatus indicates an expected call of SetB2BCompanyStatus.
func (mr *MockB2BCompanyAPIMockRecorder) SetB2BCompanyStatus(ctx, companyID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetB2BCompanyStatus", reflect.TypeOf((*MockB2BCompanyAPI)(nil).SetB2BCompanyStatus), ctx, companyID, action)
}

// UpdateB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BAddress(ctx context.Context, addressID int, payload bigcommerce.B2BAddressCreate) (*bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BAddress", ctx, addressID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BAddress indicates an expected call of UpdateB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BAddress(ctx, addressID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BAddress), ctx, addressID, payload)
}

// UpdateB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BCompany(ctx context.Context, companyID int, payload bigcommerce.B2BCompanyUpdate) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BCompany", ctx, companyID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BCompany indicates an expected call of UpdateB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BCompany(ctx, companyID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BCompany), ctx, companyID, payload)
}

// UpdateB2BCompanyCatalog mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BCompanyCatalog(ctx context.Context, companyID int, catalogID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BCompanyCatalog", ctx, companyID, catalogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateB2BCompanyCatalog indicates an expected call of UpdateB2BCompanyCatalog.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BCompanyCatalog(ctx, companyID, catalogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BCompanyCatalog", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BCompanyCatalog), ctx, companyID, catalogID)
}

// UpdateB2BCompanySuperAdminAssignments mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BCompanySuperAdminAssignments(ctx context.Context, companyID int, assignments []bigcommerce.B2BCompanySuperAdminAssignment) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BCompanySuperAdminAssignments", ctx, companyID, assignments)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BCompanySuperAdminAssignments indicates an expected call of UpdateB2BCompanySuperAdminAssignments.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BCompanySuperAdminAssignments(ctx, companyID, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BCompanySuperAdminAssignments", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BCompanySuperAdminAssignments), ctx, companyID, assignments)
}

// UpdateB2BOrder mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BOrder(ctx context.Context, bcOrderID int, payload bigcommerce.B2BOrderUpdate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BOrder", ctx, bcOrderID, payload)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BOrder indicates an expected call of UpdateB2BOrder.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BOrder(ctx, bcOrderID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BOrder", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BOrder), ctx, bcOrderID, payload)
}

// UpdateB2BPermission mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BPermission(ctx context.Context, permissionID int, payload bigcommerce.B2BPermissionCreate) (*bigcommerce.B2BPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BPermission", ctx, permissionID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BPermission indicates an expected call of UpdateB2BPermission.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BPermission(ctx, permissionID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BPermission", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BPermission), ctx, permissionID, payload)
}

// UpdateB2BQuote mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BQuote(ctx context.Context, quoteID int, body map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BQuote", ctx, quoteID, body)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BQuote indicates an expected call of UpdateB2BQuote.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BQuote(ctx, quoteID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BQuote", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BQuote), ctx, quoteID, body)
}

// UpdateB2BRole mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BRole(ctx context.Context, roleID int, payload bigcommerce.B2BRoleCreate) (*bigcommerce.B2BRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BRole", ctx, roleID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BRole indicates an expected call of UpdateB2BRole.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BRole(ctx, roleID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BRole", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BRole), ctx, roleID, payload)
}

// UpdateB2BSalesStaffAssignments mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BSalesStaffAssignments(ctx context.Context, salesStaffID int, assignments []bigcommerce.B2BSalesStaffAssignment) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BSalesStaffAssignments", ctx, salesStaffID, assignments)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BSalesStaffAssignments indicates an expected call of UpdateB2BSalesStaffAssignments.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BSalesStaffAssignments(ctx, salesStaffID, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BSalesStaffAssignments", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BSalesStaffAssignments), ctx, salesStaffID, assignments)
}

// UpdateB2BShoppingList mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BShoppingList(ctx context.Context, shoppingListID int, payload bigcommerce.B2BShoppingListUpdate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BShoppingList", ctx, shoppingListID, payload)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BShoppingList indicates an expected call of UpdateB2BShoppingList.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BShoppingList(ctx, shoppingListID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BShoppingList", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BShoppingList), ctx, shoppingListID, payload)
}

// UpdateB2BSuperAdmin mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BSuperAdmin(ctx context.Context, superAdminID int, payload bigcommerce.B2BSuperAdminUpdate) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BSuperAdmin", ctx, superAdminID, payload)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BSuperAdmin indicates an expected call of UpdateB2BSuperAdmin.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BSuperAdmin(ctx, superAdminID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BSuperAdmin", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BSuperAdmin), ctx, superAdminID, payload)
}

// UpdateB2BSuperAdminCompanyAssignments mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BSuperAdminCompanyAssignments(ctx context.Context, superAdminID int, assignments []bigcommerce.B2BSuperAdminCompanyAssignment) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BSuperAdminCompanyAssignments", ctx, superAdminID, assignments)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BSuperAdminCompanyAssignments indicates an expected call of UpdateB2BSuperAdminCompanyAssignments.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BSuperAdminCompanyAssignments(ctx, superAdminID, assignments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BSuperAdminCompanyAssignments", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BSuperAdminCompanyAssignments), ctx, superAdminID, assignments)
}

// UpdateB2BUser mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BUser(ctx context.Context, userID int, payload bigcommerce.B2BUserUpdate) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BUser", ctx, userID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BUser indicates an expected call of UpdateB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BUser(ctx, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BUser), ctx, userID, payload)
}

// MockBCCustomerManager is a mock of BCCustomerManager interface.
type MockBCCustomerManager struct {
	ctrl     *gomock.Controller
	recorder *MockBCCustomerManagerMockRecorder
	isgomock struct{}
}

// MockBCCustomerManagerMockRecorder is the mock recorder for MockBCCustomerManager.
type MockBCCustomerManagerMockRecorder struct {
	mock *MockBCCustomerManager
}

// NewMockBCCustomerManager creates a new mock instance.
func NewMockBCCustomerManager(ctrl *gomock.Controller) *MockBCCustomerManager {
	mock := &MockBCCustomerManager{ctrl: ctrl}
	mock.recorder = &MockBCCustomerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBCCustomerManager) EXPECT() *MockBCCustomerManagerMockRecorder {
	return m.recorder
}

// DeleteCustomers mocks base method.
func (m *MockBCCustomerManager) DeleteCustomers(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomers", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomers indicates an expected call of DeleteCustomers.
func (mr *MockBCCustomerManagerMockRecorder) DeleteCustomers(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomers", reflect.TypeOf((*MockBCCustomerManager)(nil).DeleteCustomers), ctx, ids)
}

// SearchCustomers mocks base method.
func (m *MockBCCustomerManager) SearchCustomers(ctx context.Context, params map[string]string) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomers", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCustomers indicates an expected call of SearchCustomers.
func (mr *MockBCCustomerManagerMockRecorder) SearchCustomers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomers", reflect.TypeOf((*MockBCCustomerManager)(nil).SearchCustomers), ctx, params)
}
