// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/b2b/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/tools/b2b/interfaces.go -destination=internal/tools/b2b/mock_bc_test.go -package=b2b_test
//

// Package b2b_test is a generated GoMock package.
package b2b_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockB2BCompanyAPI is a mock of B2BCompanyAPI interface.
type MockB2BCompanyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockB2BCompanyAPIMockRecorder
	isgomock struct{}
}

// MockB2BCompanyAPIMockRecorder is the mock recorder for MockB2BCompanyAPI.
type MockB2BCompanyAPIMockRecorder struct {
	mock *MockB2BCompanyAPI
}

// NewMockB2BCompanyAPI creates a new mock instance.
func NewMockB2BCompanyAPI(ctrl *gomock.Controller) *MockB2BCompanyAPI {
	mock := &MockB2BCompanyAPI{ctrl: ctrl}
	mock.recorder = &MockB2BCompanyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockB2BCompanyAPI) EXPECT() *MockB2BCompanyAPIMockRecorder {
	return m.recorder
}

// CreateB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BAddress(ctx context.Context, payload bigcommerce.B2BAddressCreate) (*bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BAddress", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BAddress indicates an expected call of CreateB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BAddress(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BAddress), ctx, payload)
}

// CreateB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BCompany(ctx context.Context, payload bigcommerce.B2BCompanyCreate) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BCompany", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BCompany indicates an expected call of CreateB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BCompany(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BCompany), ctx, payload)
}

// CreateB2BUser mocks base method.
func (m *MockB2BCompanyAPI) CreateB2BUser(ctx context.Context, payload bigcommerce.B2BUserCreate) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateB2BUser", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateB2BUser indicates an expected call of CreateB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) CreateB2BUser(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).CreateB2BUser), ctx, payload)
}

// DeleteB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BAddress(ctx context.Context, addressID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BAddress", ctx, addressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BAddress indicates an expected call of DeleteB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BAddress(ctx, addressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BAddress), ctx, addressID)
}

// DeleteB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BCompany(ctx context.Context, companyID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BCompany", ctx, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BCompany indicates an expected call of DeleteB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BCompany), ctx, companyID)
}

// DeleteB2BUser mocks base method.
func (m *MockB2BCompanyAPI) DeleteB2BUser(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteB2BUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteB2BUser indicates an expected call of DeleteB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) DeleteB2BUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).DeleteB2BUser), ctx, userID)
}

// GetB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) GetB2BCompany(ctx context.Context, companyID int) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB2BCompany", ctx, companyID)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetB2BCompany indicates an expected call of GetB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) GetB2BCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).GetB2BCompany), ctx, companyID)
}

// ListB2BAddresses mocks base method.
func (m *MockB2BCompanyAPI) ListB2BAddresses(ctx context.Context, params string) ([]bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BAddresses", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BAddresses indicates an expected call of ListB2BAddresses.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BAddresses(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BAddresses", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BAddresses), ctx, params)
}

// ListB2BCompanies mocks base method.
func (m *MockB2BCompanyAPI) ListB2BCompanies(ctx context.Context, params string) ([]bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BCompanies", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BCompanies indicates an expected call of ListB2BCompanies.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BCompanies(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BCompanies", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BCompanies), ctx, params)
}

// ListB2BUsers mocks base method.
func (m *MockB2BCompanyAPI) ListB2BUsers(ctx context.Context, params string) ([]bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListB2BUsers", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListB2BUsers indicates an expected call of ListB2BUsers.
func (mr *MockB2BCompanyAPIMockRecorder) ListB2BUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListB2BUsers", reflect.TypeOf((*MockB2BCompanyAPI)(nil).ListB2BUsers), ctx, params)
}

// SetB2BCompanyStatus mocks base method.
func (m *MockB2BCompanyAPI) SetB2BCompanyStatus(ctx context.Context, companyID int, action string) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetB2BCompanyStatus", ctx, companyID, action)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetB2BCompanyStatus indicates an expected call of SetB2BCompanyStatus.
func (mr *MockB2BCompanyAPIMockRecorder) SetB2BCompanyStatus(ctx, companyID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetB2BCompanyStatus", reflect.TypeOf((*MockB2BCompanyAPI)(nil).SetB2BCompanyStatus), ctx, companyID, action)
}

// UpdateB2BAddress mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BAddress(ctx context.Context, addressID int, payload bigcommerce.B2BAddressCreate) (*bigcommerce.B2BAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BAddress", ctx, addressID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BAddress indicates an expected call of UpdateB2BAddress.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BAddress(ctx, addressID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BAddress", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BAddress), ctx, addressID, payload)
}

// UpdateB2BCompany mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BCompany(ctx context.Context, companyID int, payload bigcommerce.B2BCompanyUpdate) (*bigcommerce.B2BCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BCompany", ctx, companyID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BCompany indicates an expected call of UpdateB2BCompany.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BCompany(ctx, companyID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BCompany", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BCompany), ctx, companyID, payload)
}

// UpdateB2BUser mocks base method.
func (m *MockB2BCompanyAPI) UpdateB2BUser(ctx context.Context, userID int, payload bigcommerce.B2BUserUpdate) (*bigcommerce.B2BUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateB2BUser", ctx, userID, payload)
	ret0, _ := ret[0].(*bigcommerce.B2BUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateB2BUser indicates an expected call of UpdateB2BUser.
func (mr *MockB2BCompanyAPIMockRecorder) UpdateB2BUser(ctx, userID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateB2BUser", reflect.TypeOf((*MockB2BCompanyAPI)(nil).UpdateB2BUser), ctx, userID, payload)
}

// MockBCCustomerManager is a mock of BCCustomerManager interface.
type MockBCCustomerManager struct {
	ctrl     *gomock.Controller
	recorder *MockBCCustomerManagerMockRecorder
	isgomock struct{}
}

// MockBCCustomerManagerMockRecorder is the mock recorder for MockBCCustomerManager.
type MockBCCustomerManagerMockRecorder struct {
	mock *MockBCCustomerManager
}

// NewMockBCCustomerManager creates a new mock instance.
func NewMockBCCustomerManager(ctrl *gomock.Controller) *MockBCCustomerManager {
	mock := &MockBCCustomerManager{ctrl: ctrl}
	mock.recorder = &MockBCCustomerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBCCustomerManager) EXPECT() *MockBCCustomerManagerMockRecorder {
	return m.recorder
}

// DeleteCustomers mocks base method.
func (m *MockBCCustomerManager) DeleteCustomers(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomers", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomers indicates an expected call of DeleteCustomers.
func (mr *MockBCCustomerManagerMockRecorder) DeleteCustomers(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomers", reflect.TypeOf((*MockBCCustomerManager)(nil).DeleteCustomers), ctx, ids)
}

// SearchCustomers mocks base method.
func (m *MockBCCustomerManager) SearchCustomers(ctx context.Context, params map[string]string) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomers", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCustomers indicates an expected call of SearchCustomers.
func (mr *MockBCCustomerManagerMockRecorder) SearchCustomers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomers", reflect.TypeOf((*MockBCCustomerManager)(nil).SearchCustomers), ctx, params)
}
