// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/customers/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/tools/customers/interfaces.go -destination=internal/tools/customers/mock_bc_test.go -package=customers_test
//

// Package customers_test is a generated GoMock package.
package customers_test

import (
	context "context"
	"encoding/json"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockBigCommerceCustomersAPI is a mock of BigCommerceCustomersAPI interface.
type MockBigCommerceCustomersAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBigCommerceCustomersAPIMockRecorder
	isgomock struct{}
}

// MockBigCommerceCustomersAPIMockRecorder is the mock recorder for MockBigCommerceCustomersAPI.
type MockBigCommerceCustomersAPIMockRecorder struct {
	mock *MockBigCommerceCustomersAPI
}

// NewMockBigCommerceCustomersAPI creates a new mock instance.
func NewMockBigCommerceCustomersAPI(ctrl *gomock.Controller) *MockBigCommerceCustomersAPI {
	mock := &MockBigCommerceCustomersAPI{ctrl: ctrl}
	mock.recorder = &MockBigCommerceCustomersAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBigCommerceCustomersAPI) EXPECT() *MockBigCommerceCustomersAPIMockRecorder {
	return m.recorder
}

// CountCustomerGroups mocks base method.
func (m *MockBigCommerceCustomersAPI) CountCustomerGroups(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCustomerGroups", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCustomerGroups indicates an expected call of CountCustomerGroups.
func (mr *MockBigCommerceCustomersAPIMockRecorder) CountCustomerGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCustomerGroups", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CountCustomerGroups), ctx)
}

// CreateCustomerGroup mocks base method.
func (m *MockBigCommerceCustomersAPI) CreateCustomerGroup(ctx context.Context, payload bigcommerce.CustomerGroupCreate) (*bigcommerce.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerGroup", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomerGroup indicates an expected call of CreateCustomerGroup.
func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomerGroup(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerGroup", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomerGroup), ctx, payload)
}

// DeleteCustomerGroup mocks base method.
func (m *MockBigCommerceCustomersAPI) DeleteCustomerGroup(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomerGroup indicates an expected call of DeleteCustomerGroup.
func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerGroup", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerGroup), ctx, id)
}

// GetCustomerGroup mocks base method.
func (m *MockBigCommerceCustomersAPI) GetCustomerGroup(ctx context.Context, id int) (*bigcommerce.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerGroup", ctx, id)
	ret0, _ := ret[0].(*bigcommerce.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerGroup indicates an expected call of GetCustomerGroup.
func (mr *MockBigCommerceCustomersAPIMockRecorder) GetCustomerGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerGroup", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetCustomerGroup), ctx, id)
}

// ListCustomerGroups mocks base method.
func (m *MockBigCommerceCustomersAPI) ListCustomerGroups(ctx context.Context, params map[string]string) ([]bigcommerce.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomerGroups", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomerGroups indicates an expected call of ListCustomerGroups.
func (mr *MockBigCommerceCustomersAPIMockRecorder) ListCustomerGroups(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomerGroups", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListCustomerGroups), ctx, params)
}

// UpdateCustomerGroup mocks base method.
func (m *MockBigCommerceCustomersAPI) UpdateCustomerGroup(ctx context.Context, id int, payload bigcommerce.CustomerGroupUpdate) (*bigcommerce.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerGroup", ctx, id, payload)
	ret0, _ := ret[0].(*bigcommerce.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomerGroup indicates an expected call of UpdateCustomerGroup.
func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerGroup(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerGroup", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerGroup), ctx, id, payload)
}

func (m *MockBigCommerceCustomersAPI) SearchCustomers(ctx context.Context, params map[string]string) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomers", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchCustomers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomers", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchCustomers), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) GetCustomersByIDs(ctx context.Context, ids []int) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersByIDs", ctx, ids)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetCustomersByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersByIDs", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetCustomersByIDs), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) CreateCustomers(ctx context.Context, payload []bigcommerce.CustomerCreate) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomers", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomers(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomers", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomers), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomers(ctx context.Context, payload []bigcommerce.CustomerUpdate) ([]bigcommerce.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomers", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomers(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomers", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomers), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomers(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomers", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomers(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomers", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomers), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) SearchCustomerAddresses(ctx context.Context, params map[string]string) ([]bigcommerce.CustomerAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomerAddresses", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.CustomerAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchCustomerAddresses(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomerAddresses", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchCustomerAddresses), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) CreateCustomerAddresses(ctx context.Context, payload []bigcommerce.CustomerAddressCreate) ([]bigcommerce.CustomerAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerAddresses", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.CustomerAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomerAddresses(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerAddresses", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomerAddresses), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomerAddresses(ctx context.Context, payload []bigcommerce.CustomerAddressUpdate) ([]bigcommerce.CustomerAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerAddresses", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.CustomerAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerAddresses(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerAddresses", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerAddresses), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomerAddresses(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerAddresses", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerAddresses(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerAddresses", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerAddresses), ctx, ids)
}

// Customer attributes

func (m *MockBigCommerceCustomersAPI) SearchCustomerAttributes(ctx context.Context, params map[string]string) ([]bigcommerce.CustomerAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomerAttributes", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchCustomerAttributes(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomerAttributes", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchCustomerAttributes), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) GetCustomerAttributesByIDs(ctx context.Context, ids []int) ([]bigcommerce.CustomerAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerAttributesByIDs", ctx, ids)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetCustomerAttributesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerAttributesByIDs", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetCustomerAttributesByIDs), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) CreateCustomerAttributes(ctx context.Context, payload []bigcommerce.CustomerAttributeCreate) ([]bigcommerce.CustomerAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerAttributes", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomerAttributes(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerAttributes", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomerAttributes), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomerAttributes(ctx context.Context, payload []bigcommerce.CustomerAttributeUpdate) ([]bigcommerce.CustomerAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerAttributes", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerAttributes(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerAttributes", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerAttributes), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomerAttributes(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerAttributes", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerAttributes(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerAttributes", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerAttributes), ctx, ids)
}

// Customer attribute values

func (m *MockBigCommerceCustomersAPI) SearchCustomerAttributeValues(ctx context.Context, params map[string]string) ([]bigcommerce.CustomerAttributeValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomerAttributeValues", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttributeValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchCustomerAttributeValues(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomerAttributeValues", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchCustomerAttributeValues), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) UpsertCustomerAttributeValues(ctx context.Context, payload []bigcommerce.CustomerAttributeValueUpsert) ([]bigcommerce.CustomerAttributeValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCustomerAttributeValues", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.CustomerAttributeValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpsertCustomerAttributeValues(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCustomerAttributeValues", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpsertCustomerAttributeValues), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomerAttributeValues(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerAttributeValues", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerAttributeValues(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerAttributeValues", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerAttributeValues), ctx, ids)
}

// Customer metafields

func (m *MockBigCommerceCustomersAPI) ListCustomerMetafields(ctx context.Context, customerID int) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomerMetafields", ctx, customerID)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ListCustomerMetafields(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomerMetafields", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListCustomerMetafields), ctx, customerID)
}

func (m *MockBigCommerceCustomersAPI) CreateCustomerMetafield(ctx context.Context, customerID int, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerMetafield", ctx, customerID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomerMetafield(ctx, customerID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerMetafield", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomerMetafield), ctx, customerID, mf)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomerMetafield(ctx context.Context, customerID, metafieldID int, mf bigcommerce.Metafield) (*bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerMetafield", ctx, customerID, metafieldID, mf)
	ret0, _ := ret[0].(*bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerMetafield(ctx, customerID, metafieldID, mf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerMetafield", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerMetafield), ctx, customerID, metafieldID, mf)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomerMetafield(ctx context.Context, customerID, metafieldID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerMetafield", ctx, customerID, metafieldID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerMetafield(ctx, customerID, metafieldID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerMetafield", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerMetafield), ctx, customerID, metafieldID)
}

func (m *MockBigCommerceCustomersAPI) SearchAllCustomerMetafields(ctx context.Context, params map[string]string) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAllCustomerMetafields", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchAllCustomerMetafields(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAllCustomerMetafields", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchAllCustomerMetafields), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) CreateCustomerMetafieldsBatch(ctx context.Context, payload []bigcommerce.Metafield) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerMetafieldsBatch", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateCustomerMetafieldsBatch(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerMetafieldsBatch", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateCustomerMetafieldsBatch), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomerMetafieldsBatch(ctx context.Context, payload []bigcommerce.Metafield) ([]bigcommerce.Metafield, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerMetafieldsBatch", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Metafield)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerMetafieldsBatch(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerMetafieldsBatch", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerMetafieldsBatch), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteCustomerMetafieldsBatch(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerMetafieldsBatch", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteCustomerMetafieldsBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerMetafieldsBatch", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteCustomerMetafieldsBatch), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) GetGlobalCustomerSettings(ctx context.Context) (*bigcommerce.CustomerGlobalSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalCustomerSettings", ctx)
	ret0, _ := ret[0].(*bigcommerce.CustomerGlobalSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetGlobalCustomerSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalCustomerSettings", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetGlobalCustomerSettings), ctx)
}

func (m *MockBigCommerceCustomersAPI) UpdateGlobalCustomerSettings(ctx context.Context, payload bigcommerce.CustomerGlobalSettings) (*bigcommerce.CustomerGlobalSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGlobalCustomerSettings", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.CustomerGlobalSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateGlobalCustomerSettings(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGlobalCustomerSettings", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateGlobalCustomerSettings), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) GetChannelCustomerSettings(ctx context.Context, channelID int) (*bigcommerce.CustomerChannelSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelCustomerSettings", ctx, channelID)
	ret0, _ := ret[0].(*bigcommerce.CustomerChannelSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetChannelCustomerSettings(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelCustomerSettings", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetChannelCustomerSettings), ctx, channelID)
}

func (m *MockBigCommerceCustomersAPI) UpdateChannelCustomerSettings(ctx context.Context, channelID int, payload bigcommerce.CustomerChannelSettings) (*bigcommerce.CustomerChannelSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannelCustomerSettings", ctx, channelID, payload)
	ret0, _ := ret[0].(*bigcommerce.CustomerChannelSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateChannelCustomerSettings(ctx, channelID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannelCustomerSettings", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateChannelCustomerSettings), ctx, channelID, payload)
}

func (m *MockBigCommerceCustomersAPI) GetCustomerConsent(ctx context.Context, customerID int) (*bigcommerce.CustomerConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerConsent", ctx, customerID)
	ret0, _ := ret[0].(*bigcommerce.CustomerConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetCustomerConsent(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerConsent", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetCustomerConsent), ctx, customerID)
}

func (m *MockBigCommerceCustomersAPI) UpdateCustomerConsent(ctx context.Context, customerID int, req bigcommerce.DeclareCustomerConsentRequest) (*bigcommerce.CustomerConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerConsent", ctx, customerID, req)
	ret0, _ := ret[0].(*bigcommerce.CustomerConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateCustomerConsent(ctx, customerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerConsent", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateCustomerConsent), ctx, customerID, req)
}

func (m *MockBigCommerceCustomersAPI) ListCustomerStoredInstruments(ctx context.Context, customerID int) ([]json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomerStoredInstruments", ctx, customerID)
	ret0, _ := ret[0].([]json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ListCustomerStoredInstruments(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomerStoredInstruments", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListCustomerStoredInstruments), ctx, customerID)
}

func (m *MockBigCommerceCustomersAPI) ValidateCustomerCredentials(ctx context.Context, req bigcommerce.ValidateCustomerCredentialsRequest) (*bigcommerce.ValidateCustomerCredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCustomerCredentials", ctx, req)
	ret0, _ := ret[0].(*bigcommerce.ValidateCustomerCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ValidateCustomerCredentials(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCustomerCredentials", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ValidateCustomerCredentials), ctx, req)
}

// Customer segmentation — segments

func (m *MockBigCommerceCustomersAPI) SearchSegments(ctx context.Context, params map[string]string) ([]bigcommerce.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSegments", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) SearchSegments(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSegments", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).SearchSegments), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) GetSegmentsByIDs(ctx context.Context, ids []string) ([]bigcommerce.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentsByIDs", ctx, ids)
	ret0, _ := ret[0].([]bigcommerce.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) GetSegmentsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentsByIDs", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).GetSegmentsByIDs), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) CreateSegments(ctx context.Context, payload []bigcommerce.SegmentCreate) ([]bigcommerce.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSegments", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateSegments(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSegments", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateSegments), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) UpdateSegments(ctx context.Context, payload []bigcommerce.SegmentUpdate) ([]bigcommerce.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSegments", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) UpdateSegments(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSegments", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).UpdateSegments), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteSegments(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSegments", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteSegments(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSegments", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteSegments), ctx, ids)
}

// Customer segmentation — shopper profiles for a segment

func (m *MockBigCommerceCustomersAPI) ListShopperProfilesInSegment(ctx context.Context, segmentID string) ([]bigcommerce.ShopperProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopperProfilesInSegment", ctx, segmentID)
	ret0, _ := ret[0].([]bigcommerce.ShopperProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ListShopperProfilesInSegment(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopperProfilesInSegment", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListShopperProfilesInSegment), ctx, segmentID)
}

func (m *MockBigCommerceCustomersAPI) AddShopperProfilesToSegment(ctx context.Context, segmentID string, profileIDs []string) ([]bigcommerce.ShopperProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddShopperProfilesToSegment", ctx, segmentID, profileIDs)
	ret0, _ := ret[0].([]bigcommerce.ShopperProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) AddShopperProfilesToSegment(ctx, segmentID, profileIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddShopperProfilesToSegment", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).AddShopperProfilesToSegment), ctx, segmentID, profileIDs)
}

func (m *MockBigCommerceCustomersAPI) RemoveShopperProfilesFromSegment(ctx context.Context, segmentID string, profileIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveShopperProfilesFromSegment", ctx, segmentID, profileIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) RemoveShopperProfilesFromSegment(ctx, segmentID, profileIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveShopperProfilesFromSegment", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).RemoveShopperProfilesFromSegment), ctx, segmentID, profileIDs)
}

// Customer segmentation — shopper profiles

func (m *MockBigCommerceCustomersAPI) ListShopperProfiles(ctx context.Context, params map[string]string) ([]bigcommerce.ShopperProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShopperProfiles", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.ShopperProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ListShopperProfiles(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShopperProfiles", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListShopperProfiles), ctx, params)
}

func (m *MockBigCommerceCustomersAPI) CreateShopperProfiles(ctx context.Context, payload []bigcommerce.ShopperProfileCreate) ([]bigcommerce.ShopperProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShopperProfiles", ctx, payload)
	ret0, _ := ret[0].([]bigcommerce.ShopperProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) CreateShopperProfiles(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShopperProfiles", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).CreateShopperProfiles), ctx, payload)
}

func (m *MockBigCommerceCustomersAPI) DeleteShopperProfiles(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShopperProfiles", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) DeleteShopperProfiles(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShopperProfiles", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).DeleteShopperProfiles), ctx, ids)
}

func (m *MockBigCommerceCustomersAPI) ListSegmentsForShopperProfile(ctx context.Context, profileID string) ([]bigcommerce.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSegmentsForShopperProfile", ctx, profileID)
	ret0, _ := ret[0].([]bigcommerce.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockBigCommerceCustomersAPIMockRecorder) ListSegmentsForShopperProfile(ctx, profileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSegmentsForShopperProfile", reflect.TypeOf((*MockBigCommerceCustomersAPI)(nil).ListSegmentsForShopperProfile), ctx, profileID)
}
