// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tools/storefront/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/tools/storefront/interfaces.go -destination=internal/tools/storefront/mock_bc_test.go -package=storefront_test
//

// Package storefront_test is a generated GoMock package.
package storefront_test

import (
	context "context"
	reflect "reflect"

	bigcommerce "github.com/roel-c/bc-admin-mcp/internal/bigcommerce"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptAPI is a mock of ScriptAPI interface.
type MockScriptAPI struct {
	ctrl     *gomock.Controller
	recorder *MockScriptAPIMockRecorder
	isgomock struct{}
}

// MockScriptAPIMockRecorder is the mock recorder for MockScriptAPI.
type MockScriptAPIMockRecorder struct {
	mock *MockScriptAPI
}

// NewMockScriptAPI creates a new mock instance.
func NewMockScriptAPI(ctrl *gomock.Controller) *MockScriptAPI {
	mock := &MockScriptAPI{ctrl: ctrl}
	mock.recorder = &MockScriptAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptAPI) EXPECT() *MockScriptAPIMockRecorder {
	return m.recorder
}

// ListScripts mocks base method.
func (m *MockScriptAPI) ListScripts(ctx context.Context, params bigcommerce.ScriptListParams) ([]bigcommerce.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScripts", ctx, params)
	ret0, _ := ret[0].([]bigcommerce.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScripts indicates an expected call of ListScripts.
func (mr *MockScriptAPIMockRecorder) ListScripts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScripts", reflect.TypeOf((*MockScriptAPI)(nil).ListScripts), ctx, params)
}

// GetScript mocks base method.
func (m *MockScriptAPI) GetScript(ctx context.Context, uuid string) (*bigcommerce.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScript", ctx, uuid)
	ret0, _ := ret[0].(*bigcommerce.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScript indicates an expected call of GetScript.
func (mr *MockScriptAPIMockRecorder) GetScript(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScript", reflect.TypeOf((*MockScriptAPI)(nil).GetScript), ctx, uuid)
}

// CreateScript mocks base method.
func (m *MockScriptAPI) CreateScript(ctx context.Context, payload bigcommerce.ScriptCreate) (*bigcommerce.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScript", ctx, payload)
	ret0, _ := ret[0].(*bigcommerce.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScript indicates an expected call of CreateScript.
func (mr *MockScriptAPIMockRecorder) CreateScript(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScript", reflect.TypeOf((*MockScriptAPI)(nil).CreateScript), ctx, payload)
}

// UpdateScript mocks base method.
func (m *MockScriptAPI) UpdateScript(ctx context.Context, uuid string, payload bigcommerce.ScriptUpdate) (*bigcommerce.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScript", ctx, uuid, payload)
	ret0, _ := ret[0].(*bigcommerce.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScript indicates an expected call of UpdateScript.
func (mr *MockScriptAPIMockRecorder) UpdateScript(ctx, uuid, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScript", reflect.TypeOf((*MockScriptAPI)(nil).UpdateScript), ctx, uuid, payload)
}

// DeleteScript mocks base method.
func (m *MockScriptAPI) DeleteScript(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScript", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScript indicates an expected call of DeleteScript.
func (mr *MockScriptAPIMockRecorder) DeleteScript(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScript", reflect.TypeOf((*MockScriptAPI)(nil).DeleteScript), ctx, uuid)
}
